### ISSUE TITLE
Static methods in generics can't be inherited

### ISSUE THREAD

**Issue by RReverser** [BlackWhiteYoshi/InlineComposition#2]
It seems that, when expanding generics, the generator can currently only substitute individual params but not the entire struct at once.

For example, if I have a struct like (minimised example)

```cs
[InlineBase]
public readonly struct BigInt<TUpper, TLower>
{
  public static bool operator >(BigInt<TUpper, TLower> left, BigInt<TUpper, TLower> right) => false;
}

[Inline<BigInt<ulong, ulong>>]
public readonly partial struct U128 {}
```

then the source generator fails with

```
CSC : warning CS8785: Generator 'InlineCompositionGenerator' failed to generate source. It will not contribute to the output and comp 
ilation errors may occur as a result. Exception was of type 'Exception' with message 'No Match for parameterType BigInt<TUpper, TLower>: Microsoft.CodeAnalysis.CSharp.Syntax.GenericNameSyntax'.
```

As far as I can tell, it's coming from [this loop](https://github.com/BlackWhiteYoshi/InlineComposition/blob/4ce3cda111b2a442ab0152d8a2045eb784ecbd1e/InlineComposition/InlineCompositionGenerator.cs#L547-L568) which only looks for identifiers and primitives, but struggles with a `GenericNameSyntax` node representing the whole `BigInt<TUpper, TLower>`.

In other situation I could easily add `TSelf` to work around this issue, but operator overloads strictly require at least one of the arguments to be exactly same type as the parent, and they have no way of knowing that `TSelf` is indeed same type, so I have to spell out the whole `BigInt<...>` instead.

**Comment by BlackWhiteYoshi** [comment]
Thank you for pointing out this issue.

Inlining generic classes/structs are possible, but that is more like an experimental feature. I have implemented it in a quick and simple way. Actually, the whole package is somewhat quick and dirty.

Anyway, you are right, there was (at least) one missing case in that loop. After revisiting the code, I noticed that the created string is used as key to map overloads, so I can just do *ToString()* on the type directly instead of all these checks.

After checking your example, I also noticed that there are 2 other things not working.  
1. I did not use *ReplaceGenerics()* in the *methodHead*. So, the *returnType* and parameters in methods got never replaced.  
2. *operator* methods did not get handled at all.

I fixed all 3 issues in the newest version, but your use case will still not work. When *U128* inlines the *BigInt<>* operator method, both parameters will be still of the type *BitInt<>* and not *U128*.

If you find more issues or I broke something while implementing these fixes, feel free to create another issue.

**Comment by RReverser** [comment]
Thanks for the quick turnaround. This package might be a hack for now, but so far it's the closest to what I envisioned and hoped to find on NuGet :)

> I fixed all 3 issues in the newest version, but your use case will still not work. When _U128_ inlines the _BigInt<>_ operator method, both parameters will be still of the type _BitInt<>_ and not _U128_.

Ah that still makes it not very usable for me for now, yeah. All the `operator`s are by far the largest chunk of boilerplate for me.

But I don't understand, if you're saying

> I did not use ReplaceGenerics() in the methodHead. So, the returnType and parameters in methods got never replaced.

is fixed now, shouldn't those parameters be replaced as well?

**Comment by BlackWhiteYoshi** [comment]
generic parameters are replaced. For example

```csharp
[InlineBase]
public struct Example<T> {
    public static T Add(Example<T> left, T right) => default!;
}

[Inline<Example<int>>]
public partial struct ExampleDerived;
```

will replace all occurrences of *T* with the given typeparameter *int*

```csharp
// generated code

[Inline<Example<int>>]
public partial struct ExampleDerived {
    public static int Add(Example<int> left, int right) {
        {
            return default!;
        }
    }
}
```

The "BaseClass"-type *Example* is not replaced by anything.

**Comment by RReverser** [comment]
Ah that makes sense.

Still, replacing instances of the same generic (even if comparing type by literally `.ToString()`, although should be even easier via semantic model) could be very useful.

**Comment by BlackWhiteYoshi** [comment]
In the newest version (1.2.0) I added a property *MapBaseType*, if enabled, all occurrences of the type of the inlineBase class/struct get replaced with the type of the inlining class/struct:

```csharp
[InlineBase(MapBaseType = true)]
public struct Example<T> {
    public static T Add(Example<T> left, T right) => default!;

    public static bool operator &(Example<T> left, Example<T> right) => false;
}

[Inline<Example<int>>]
public partial struct ExampleDerived;
```

```csharp
// <auto-generated/>
public partial struct ExampleDerived {
    public static int Add(ExampleDerived left, int right) => default!;

    public static bool operator &(ExampleDerived left, ExampleDerived right) => false;
}
```

Your use case should now work with this option enabled. If you have still any problems or find any bugs, let me know :)

**Comment by RReverser** [comment]
Great, thanks, can't wait to try it out :)
