### ISSUE TITLE
MapBaseType does not apply to base interfaces

### ISSUE THREAD

**Issue by RReverser** [BlackWhiteYoshi/InlineComposition#4]
I tried out `MapBaseType` from #2, and it works great in the method declarations and bodies, but doesn't seem to apply to interface list.

For example,

```cs
[InlineBase(MapBaseType = true)]
[StructLayout(LayoutKind.Sequential)]
readonly struct BigInt<TUpper, TLower>
    : IEquatable<BigInt<TUpper, TLower>>,
        IComparable,
        IComparable<BigInt<TUpper, TLower>>
    where TUpper : unmanaged, IComparable<TUpper>
    where TLower : unmanaged, IComparable<TLower>
{
// ...

    public int CompareTo(BigInt<TUpper, TLower> other) =>
        upper.CompareTo(other.upper) switch
        {
            0 => lower.CompareTo(other.lower),
            var cmp => cmp
        };
}

[Inline<BigInt<ulong, ulong>>]
public readonly partial struct MyU128 { }
```

ends up expanded as

```cs
public readonly partial struct MyU128 : IEquatable<BigInt<TUpper, TLower>>, IComparable, IComparable<BigInt<TUpper, TLower>>
{
	public int CompareTo(MyU128 other)
	{
		{
			return upper.CompareTo(other.upper) switch
			{
				0 => lower.CompareTo(other.lower),
				var cmp => cmp
			};
		}
	}

}
```

so the generated methods has a correct signature but the interface doesn't match it anymore.

Also the `where` clauses got lost.

**Comment by RReverser** [comment]
While at it, also noticed that attribute `[StructLayout(LayoutKind.Sequential)]` didn't get copied over. Not sure if that's expected, but would be nice if it could be.

**Comment by BlackWhiteYoshi** [comment]
The baselist (inheritance and interfaces) and primary constructor parameters were missing a ReplaceGeneric() call, so generics and basetypes did not get replaced. I fixed both in the newest version (1.3.0).


For the attributes it is intended to not inline those, because for example if you have 2 structs with both having [InlineBase] and [StructLayout] and want to inline both in one struct, you get a struct with 2 [StructLayout] what leads to a compile error.
So I decided to make this optional and added an additional property *InlineAttributes* to [InlineBase]:

```csharp
using InlineCompositionAttributes;

[SomeAttribute]
[InlineBase(InlineAttributes = true)]
public class Example { ... }

[Inline<Example>]
public partial class Derived { ... }


[...]


// <auto-generated/>
[SomeAttribute]
public partial class Derived { ... }
```

This works now with the newest version (1.3.0).

I forgot about the *where* clauses and never implemented something to handle them. They are currently still not handled. but I will fix that in the next version.

**Comment by RReverser** [comment]
Ok awesome, thanks! I'll keep this open for the `where` clauses for now.

**Comment by BlackWhiteYoshi** [comment]
After some testing, the generated code produces a compile error and then I realize, ignoring the constraint clauses is actually the right thing to do. When inlining a generic type, the type parameters get filled in with concrete types, so the generated code does not have any type parameters any more.

When we take your example (with the baselist fix and adding constraint clauses) we get:

```csharp
// <auto-generated/>
public readonly partial struct MyU128 : IEquatable<MyU128>, IComparable, IComparable<MyU128>
    where TUpper : unmanaged, IComparable<TUpper>
    where TLower : unmanaged, IComparable<TLower>
{ ...
```

You can see that *TUpper* and *TLower* are not defined anymore, so the constraint clauses just causing compile errors.

**Comment by RReverser** [comment]
Oh right, that's a very good point. I think I only noticed missing `where` because interfaces didn't inline the generics at the time. You're right `where` shouldn't be copied.
